version: v2beta1
name: api

pipelines:
  dev:
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      create_deployments --all
      start_dev ui
  deploy:
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      build_images --all -t $(git describe --always)
      create_deployments --all

images:
  ui:
    image: ghcr.io/sun-asterisk-research/shope-shop/ui
    buildArgs:
      PUBLIC_USERNAME_DEFAULT: "customer1935"

deployments:
  ui:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        containers:
          - image: ghcr.io/sun-asterisk-research/shope-shop/ui
            resources:
              requests:
                cpu: 1m
                memory: 60Mi
              limits:
                cpu: 200m
                memory: 256Mi
        service:
          ports:
            - port: 3000

dev:
  ui:
    labelSelector:
      app.kubernetes.io/component: ui
    devImage: node:20
    command: ["./devspace_start.sh"]
    workingDir: /ui
    sync:
      - path: ./
        uploadExcludePaths:
          - node_modules
        startContainer: true
    persistPaths:
      - path: /ui/node_modules
    ports:
      - port: "5173"

profiles:
  - name: production
    patches:
      - op: replace
        path: deployments.ui.helm.values.ingress
        value:
          name: shope-ui
          ingressClass: nginx
          rules:
            - host: shope.sun-asterisk.ai
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: ui
                        port:
                          number: 3000
