version: v2beta1
name: api

pipelines:
  dev:
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      create_deployments --all
      start_dev api
  deploy:
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      build_images --all -t $(git describe --always)
      create_deployments --all

images:
  api:
    image: ghcr.io/sun-asterisk-research/shope-shop/api

deployments:
  api:
    helm:
      chart:
        name: component-chart
        repo: https://charts.devspace.sh
      values:
        replicas: 3
        containers:
          - image: ghcr.io/sun-asterisk-research/shope-shop/api
            env:
              - name: DATABASE_URL
                value: mongodb://shope:secret@mongodb:27017/shope
              - name: JWT_SECRET
                value: secret
            resources:
              requests:
                cpu: 2m
                memory: 120Mi
              limits:
                cpu: 500m
                memory: 512Mi
        service:
          ports:
            - port: 3000

  mongodb:
    helm:
      chart:
        name: mongodb
        repo: https://charts.bitnami.com/bitnami
      values:
        # https://artifacthub.io/packages/helm/bitnami/mongodb
        architecture: "standalone"
        image:
          repository: bitnami/mongodb
          tag: "7.0.2-debian-11-r0"
        auth:
          databases: ["shope"]
          usernames: ["shope"]
          passwords: ["secret"]
        resources:
          requests:
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: "1"
            memory: 1Gi

dev:
  api:
    labelSelector:
      app.kubernetes.io/component: api
    devImage: oven/bun:1
    command: ["./devspace_start.sh"]
    env:
      - name: NODE_ENV
        value: development
    workingDir: /api
    sync:
      - path: ./
        uploadExcludePaths:
          - node_modules
        startContainer: true
    persistPaths:
      - path: /api/node_modules
    ports:
      - port: "3000"

profiles:
  - name: production
    patches:
      - op: replace
        path: deployments.api.helm.values.replicas
        value: 3
      - op: replace
        path: deployments.api.helm.values.ingress
        value:
          name: shope-api
          ingressClass: nginx
          rules:
            - host: shopeapi.sun-asterisk.ai
              http:
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: api
                        port:
                          number: 3000
